/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { ApiResponseStringStatus } from "./apiResponseStringStatus";

export interface ApiResponseString {
  data?: string;
  message?: string;
  status?: ApiResponseStringStatus;
}
