/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { GetImageRespDto } from "./getImageRespDto";
import type { ApiResponseListGetImageRespDtoStatus } from "./apiResponseListGetImageRespDtoStatus";

export interface ApiResponseListGetImageRespDto {
  data: GetImageRespDto[];
  message?: string;
  status?: ApiResponseListGetImageRespDtoStatus;
}
