/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { GetProfileImgRespDto } from "./getProfileImgRespDto";
import type { ApiResponseGetProfileImgRespDtoStatus } from "./apiResponseGetProfileImgRespDtoStatus";

export interface ApiResponseGetProfileImgRespDto {
  data?: GetProfileImgRespDto;
  message?: string;
  status?: ApiResponseGetProfileImgRespDtoStatus;
}
