/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { GetDetailPostRespDto } from "./getDetailPostRespDto";
import type { ApiResponseGetDetailPostRespDtoStatus } from "./apiResponseGetDetailPostRespDtoStatus";

export interface ApiResponseGetDetailPostRespDto {
  data?: GetDetailPostRespDto;
  message?: string;
  status?: ApiResponseGetDetailPostRespDtoStatus;
}
