/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { GetHospitalInfoRespDto } from "./getHospitalInfoRespDto";
import type { ApiResponseListGetHospitalInfoRespDtoStatus } from "./apiResponseListGetHospitalInfoRespDtoStatus";

export interface ApiResponseListGetHospitalInfoRespDto {
  data?: GetHospitalInfoRespDto[];
  message?: string;
  status?: ApiResponseListGetHospitalInfoRespDtoStatus;
}
