/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { GetUserRespDto } from "./getUserRespDto";
import type { ApiResponseGetUserRespDtoStatus } from "./apiResponseGetUserRespDtoStatus";

export interface ApiResponseGetUserRespDto {
  data?: GetUserRespDto;
  message?: string;
  status?: ApiResponseGetUserRespDtoStatus;
}
