/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { GetCommentRespDto } from "./getCommentRespDto";
import type { ApiResponseListGetCommentRespDtoStatus } from "./apiResponseListGetCommentRespDtoStatus";

export interface ApiResponseListGetCommentRespDto {
  data?: GetCommentRespDto[];
  message?: string;
  status?: ApiResponseListGetCommentRespDtoStatus;
}
