/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { ApiResponseLongStatus } from "./apiResponseLongStatus";

export interface ApiResponseLong {
  data?: number;
  message?: string;
  status?: ApiResponseLongStatus;
}
