/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { GetBoardRespDto } from "./getBoardRespDto";
import type { ApiResponseGetBoardRespDtoStatus } from "./apiResponseGetBoardRespDtoStatus";

export interface ApiResponseGetBoardRespDto {
  data?: GetBoardRespDto;
  message?: string;
  status?: ApiResponseGetBoardRespDtoStatus;
}
