/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { ApiResponseIntegerStatus } from "./apiResponseIntegerStatus";

export interface ApiResponseInteger {
  data?: number;
  message?: string;
  status?: ApiResponseIntegerStatus;
}
