/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { GetShelterInfoRespDto } from "./getShelterInfoRespDto";
import type { ApiResponseListGetShelterInfoRespDtoStatus } from "./apiResponseListGetShelterInfoRespDtoStatus";

export interface ApiResponseListGetShelterInfoRespDto {
  data?: GetShelterInfoRespDto[];
  message?: string;
  status?: ApiResponseListGetShelterInfoRespDtoStatus;
}
