/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { CreateCommentRespDto } from "./createCommentRespDto";
import type { ApiResponseCreateCommentRespDtoStatus } from "./apiResponseCreateCommentRespDtoStatus";

export interface ApiResponseCreateCommentRespDto {
  data?: CreateCommentRespDto;
  message?: string;
  status?: ApiResponseCreateCommentRespDtoStatus;
}
