/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { GetBoardRespDto } from './getBoardRespDto';
import type { ApiResponseListGetBoardRespDtoStatus } from './apiResponseListGetBoardRespDtoStatus';

export interface ApiResponseListGetBoardRespDto {
  data?: GetBoardRespDto[];
  message?: string;
  status?: ApiResponseListGetBoardRespDtoStatus;
}
