/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { ApiResponseVoidData } from "./apiResponseVoidData";
import type { ApiResponseVoidStatus } from "./apiResponseVoidStatus";

export interface ApiResponseVoid {
  data?: ApiResponseVoidData;
  message?: string;
  status?: ApiResponseVoidStatus;
}
