/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { CreateBoardReqDtoBoardType } from "./createBoardReqDtoBoardType";

export interface CreateBoardReqDto {
  /** 게시판 유형 */
  boardType?: CreateBoardReqDtoBoardType;
  /** 게시판 설명 */
  description?: string;
  /** 게시판 제목 */
  title?: string;
}
