/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export type CreatePostReqDtoCategory = typeof CreatePostReqDtoCategory[keyof typeof CreatePostReqDtoCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePostReqDtoCategory = {
  TECH: 'TECH',
  LIFESTYLE: 'LIFESTYLE',
  EDUCATION: 'EDUCATION',
  ENTERTAINMENT: 'ENTERTAINMENT',
} as const;
