/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export interface CreatePost2ReqDto {
  address?: string;
  /** 게시판 ID */
  boardId?: number;
  category?: string;
  /** 게시글 내용 */
  content: string;
  latitude?: number;
  longitude?: number;
  name?: string;
  regionCode?: number;
  /** 게시글 제목 */
  title: string;
}
