/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { CreatePostReqDtoCategory } from './createPostReqDtoCategory';

export interface CreatePostReqDto {
  boardId?: number;
  category: CreatePostReqDtoCategory;
  /**
   * 게시글 내용
   * @minLength 5
   * @maxLength 2147483647
   */
  content: string;
  likesCount?: number;
  /**
   * 게시글 제목
   * @minLength 5
   * @maxLength 20
   */
  title: string;
}
