/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

/**
 * 게시판 유형
 */
export type CreateBoardReqDtoBoardType =
  (typeof CreateBoardReqDtoBoardType)[keyof typeof CreateBoardReqDtoBoardType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateBoardReqDtoBoardType = {
  GENERAL: "GENERAL",
  INFO: "INFO",
} as const;
