/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export type GetBoardRespDtoBoardType =
  (typeof GetBoardRespDtoBoardType)[keyof typeof GetBoardRespDtoBoardType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetBoardRespDtoBoardType = {
  GENERAL: "GENERAL",
  INFO: "INFO",
} as const;
