/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export type GetBoardListParams = {
  pageNo?: number;
  pageSize?: number;
  sortBy?: string;
  direction?: string;
};
