/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export interface GetBoardRespDto {
  boardId?: number;
  createdAt?: string;
  description?: string;
  isDelete?: boolean;
  title?: string;
  updatedAt?: string;
}
