/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { GetBoardRespDtoBoardType } from "./getBoardRespDtoBoardType";

export interface GetBoardRespDto {
  boardId?: number;
  boardType?: GetBoardRespDtoBoardType;
  createdAt?: string;
  description?: string;
  isDelete?: boolean;
  title?: string;
  updatedAt?: string;
}
