/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export interface GetCommentRespDto {
  boardId?: number;
  commentId?: number;
  content?: string;
  createAt?: string;
  postId?: number;
  updateAt?: string;
  userId?: number;
}
