/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export interface GetDetailPostRespDto {
  boardId?: number;
  commentCount?: number;
  content?: string;
  createdAt?: string;
  postId?: number;
  title?: string;
  updatedAt?: string;
  userId?: number;
}
