/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export interface GetHospitalInfoRespDto {
  add1?: string;
  add2?: string;
  addNum?: number;
  id?: number;
  name?: string;
  tel?: string;
  type?: string;
  x?: number;
  y?: number;
}
