/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export interface GetImageRespDto {
  imageId?: number;
  imageUrl?: string;
  postId?: number;
}
