/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export interface GetListPostRespDto {
  boardId?: number;
  contentPreview?: string;
  createdAt?: string;
  id?: number;
  likesCount?: number;
  title?: string;
  updatedAt?: string;
  userId?: number;
  views?: number;
}
