/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export type GetPostsParams = {
  boardId?: number;
  keyword?: string;
  page?: number;
  size?: number;
  sort?: string;
};
