/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export interface GetShelterInfoRespDto {
  add1?: string;
  addNum?: number;
  name?: string;
  shelterId?: number;
  tel?: string;
  type?: string;
  x?: number;
  y?: number;
}
