/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { GetUserRespDtoRole } from "./getUserRespDtoRole";

export interface GetUserRespDto {
  nick?: string;
  role?: GetUserRespDtoRole;
  userId?: number;
}
