/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export type GetUserRespDtoRole =
  (typeof GetUserRespDtoRole)[keyof typeof GetUserRespDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserRespDtoRole = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;
