/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export * from "./apiResponseGetBoardRespDto";
export * from "./apiResponseGetBoardRespDtoStatus";
export * from "./apiResponseListGetBoardRespDto";
export * from "./apiResponseListGetBoardRespDtoStatus";
export * from "./apiResponseVoid";
export * from "./apiResponseVoidData";
export * from "./apiResponseVoidStatus";
export * from "./createBoardReqDto";
export * from "./createCommentReqDto";
export * from "./createPostReqDto";
export * from "./createPostReqDtoCategory";
export * from "./getBoardListParams";
export * from "./getBoardRespDto";
export * from "./getDetailPost200";
export * from "./getPosts200";
export * from "./getPostsParams";
export * from "./updateBoardReqDto";
export * from "./updatePostReqDto";
export * from "./updatePostReqDtoPostCategory";
