/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { ApiResponseVoid } from "./apiResponseVoid";
import type { ApiResponseInteger } from "./apiResponseInteger";

export type ToggleLike1200 = ApiResponseVoid | ApiResponseInteger;
