/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { UpdatePostReqDto } from "./updatePostReqDto";

export type UpdatePostParams = {
  req: UpdatePostReqDto;
};
