/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export interface UpdatePasswordReqDto {
  /** 기존 비밀번호 */
  currentPassword: string;
  /**
   * 변경할 비밀번호
   * @minLength 8
   * @maxLength 20
   * @pattern ^(?=.*[A-Z])(?=.*[0-9])(?=.*[a-z])(?=.*[!@#$%^&*()-+=]).*$
   */
  newPassword: string;
}
