/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export interface UpdateBoardReqDto {
  /** 변경하고자 하는 게시판 설명 */
  description?: string;
  /** 변경하고자 하는 게시판 제목 */
  title?: string;
}
