/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export interface UpdateNickReqDto {
  /**
   * 변경할 닉네임
   * @minLength 2
   * @maxLength 12
   */
  nick: string;
}
