/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */

export type UserCreateReqDtoRole =
  (typeof UserCreateReqDtoRole)[keyof typeof UserCreateReqDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserCreateReqDtoRole = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;
