/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BASIC PAWSTIME API
 * OpenAPI spec version: v1
 */
import type { UserCreateReqDtoRole } from "./userCreateReqDtoRole";

export interface UserCreateReqDto {
  email: string;
  /**
   * @minLength 2
   * @maxLength 12
   */
  nick: string;
  /**
   * @minLength 8
   * @maxLength 20
   * @pattern ^(?=.*[A-Z])(?=.*[0-9])(?=.*[a-z])(?=.*[!@#$%^&*()-+=]).*$
   */
  password: string;
  role?: UserCreateReqDtoRole;
}
