import type { Metadata } from "next";
import "./styles/globals.css";
import ReactQueryProvider from "./lib/providers/ReactQueryProvider";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Hearder";

export const metadata: Metadata = {
  title: "Paws-Time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col w-full h-screen">
        <ReactQueryProvider>
          <Header />
          <div className="flex flex-row flex-1">
            <Sidebar />
            <main className="flex-1 bg-white p-6 overflow-auto">
              {children}
            </main>
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
