import type { Metadata } from "next";
import "./styles/globals.css";
import ReactQueryProvider from "./lib/providers/ReactQueryProvider";
export const metadata: Metadata = {
  title: "Paws-Time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="flex flex-col w-full h-screen">
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
